"""Insert 2026-08-01 TikTok channel-details + transcript provenance changelog entries."""

from __future__ import annotations

import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

from app.services.supabase_client import get_supabase  # noqa: E402

ENTRIES = [
    {
        "published_at": "2026-08-01",
        "category": "feature",
        "title": "Richer TikTok channel-details (non-breaking)",
        "description": (
            "TikTok channel-details keeps every existing field your integrations already parse, "
            "and adds stable IDs, account age, commerce/seller flags, and bio-link risk for vetting "
            "and joins. category, private, and exact follower counts are unchanged."
        ),
        "items": [
            "New id and secUid for stable TikTok identity and chaining",
            "createTime, uniqueIdModifyTime, nickNameModifyTime for account-age and takeover signals",
            "isCommerceUser, isSeller, isOrganization, isAdVirtual, bioLinkRisk, friendCount/diggCount, avatar sizes, privacy settings, fetchedAt",
        ],
    },
    {
        "published_at": "2026-08-01",
        "category": "improvement",
        "title": "Transcript source in the JSON body (non-breaking)",
        "description": (
            "YouTube and TikTok transcript responses now include source in the body so RAG and "
            "analytics can weight caption quality vs Whisper. Existing transcript, transcriptSegments, "
            "wordCount, segments, and language fields are unchanged. YouTube also adds isAutoGenerated, "
            "isTranslated, and availableLanguages when captions are used."
        ),
        "items": [
            'source: "captions" | "whisper" (TikTok) | "fallback" (YouTube secondary path)',
            "YouTube: isAutoGenerated, isTranslated, availableLanguages[]",
            "No rename of segment fields; float seconds and ISO language codes unchanged",
        ],
    },
]

sb = get_supabase()
for entry in ENTRIES:
    existing = (
        sb.table("changelog_entries")
        .select("id")
        .eq("title", entry["title"])
        .limit(1)
        .execute()
    )
    if existing.data:
        row_id = existing.data[0]["id"]
        sb.table("changelog_entries").update(entry).eq("id", row_id).execute()
        print("updated:", entry["title"], row_id)
    else:
        res = sb.table("changelog_entries").insert(entry).execute()
        print("inserted:", entry["title"], res.data[0]["id"] if res.data else res)