"""YouTube transcript diagnostic 404 + language selection."""

from __future__ import annotations

import pytest
from fastapi import HTTPException

from app.routers import youtube as yt
from app.services import youtube_native as yn


def test_raise_transcript_unavailable_no_captions() -> None:
    with pytest.raises(HTTPException) as ei:
        yt._raise_transcript_unavailable(
            {
                "segments": [],
                "error": {
                    "code": "no_captions",
                    "reason": "YouTube published no caption tracks for this video.",
                },
                "availableLanguages": [],
                "hasAutoCaptions": False,
            },
            language=None,
        )
    assert ei.value.status_code == 404
    detail = ei.value.detail
    assert isinstance(detail, dict)
    assert detail["code"] == "no_captions"
    assert detail["availableLanguages"] == []
    assert detail["hasAutoCaptions"] is False
    assert "speech" in detail["reason"].lower() or "caption" in detail["reason"].lower()


def test_raise_transcript_unavailable_language_not_available() -> None:
    with pytest.raises(HTTPException) as ei:
        yt._raise_transcript_unavailable(
            {
                "segments": [],
                "error": {"code": "language_not_available", "reason": "No tr track."},
                "availableLanguages": [
                    {
                        "languageCode": "en",
                        "languageName": "English",
                        "isAutoGenerated": True,
                    }
                ],
                "hasAutoCaptions": True,
                "requestedLanguage": "tr",
            },
            language="tr",
        )
    detail = ei.value.detail
    assert isinstance(detail, dict)
    assert detail["code"] == "language_not_available"
    assert detail["requestedLanguage"] == "tr"
    assert detail["hasAutoCaptions"] is True
    assert detail["availableLanguages"][0]["languageCode"] == "en"


def test_rank_caption_tracks_prefers_requested_then_manual() -> None:
    tracks = [
        {"languageCode": "de", "kind": "asr", "baseUrl": "u1"},
        {"languageCode": "en", "kind": "asr", "baseUrl": "u2"},
        {"languageCode": "en", "kind": "standard", "baseUrl": "u3"},
    ]
    ranked = yn._rank_caption_tracks(tracks, "en")
    assert ranked[0]["baseUrl"] == "u3"  # matching + manual
    assert ranked[1]["baseUrl"] == "u2"  # matching + asr


def test_transcript_error_payload_shape() -> None:
    payload = yn._transcript_error_payload(
        code="no_captions",
        reason="none",
        title="Live",
        available=[],
        has_auto=False,
        requested_language="en",
    )
    assert payload["segments"] == []
    assert payload["error"]["code"] == "no_captions"
    assert payload["hasAutoCaptions"] is False
    assert payload["requestedLanguage"] == "en"
