"""Tests for YouTube audio-transcript pricing + transcript 404 suggestion."""

from __future__ import annotations

import pytest
from fastapi import HTTPException

from app.routers import youtube as yt
from app.services import youtube_audio as ya


def test_credits_for_duration() -> None:
    assert ya.credits_for_duration(1) == 2
    assert ya.credits_for_duration(60) == 2
    assert ya.credits_for_duration(61) == 4
    assert ya.credits_for_duration(12752) == 426  # ceil(212.533)*2


def test_segments_to_ms_uniform() -> None:
    segs = ya.segments_to_ms(
        [
            {"text": "Hello", "start": 0.16, "end": 1.92},
            {"text": "World", "start": 2.0, "end": 3.5},
        ]
    )
    assert segs == [
        {"text": "Hello", "startMs": 160, "endMs": 1920},
        {"text": "World", "startMs": 2000, "endMs": 3500},
    ]
    shapes = {tuple(sorted(s.keys())) for s in segs}
    assert shapes == {("endMs", "startMs", "text")}
    assert all(isinstance(s["startMs"], int) and isinstance(s["endMs"], int) for s in segs)


def test_raise_transcript_unavailable_includes_suggestion() -> None:
    with pytest.raises(HTTPException) as ei:
        yt._raise_transcript_unavailable(
            {
                "segments": [],
                "error": {
                    "code": "no_captions",
                    "reason": "YouTube publishes no caption track for this video.",
                },
                "availableLanguages": [],
                "hasAutoCaptions": False,
            },
            language=None,
            suggestion={
                "endpoint": "/v1/youtube/audio-transcript",
                "message": "Use audio-transcript",
                "estimatedCredits": 426,
                "durationSeconds": 12752,
            },
        )
    detail = ei.value.detail
    assert isinstance(detail, dict)
    assert detail["code"] == "no_captions"
    assert detail["suggestion"]["endpoint"] == "/v1/youtube/audio-transcript"
    assert detail["suggestion"]["estimatedCredits"] == 426


def test_raise_skips_suggestion_on_language_mismatch() -> None:
    with pytest.raises(HTTPException) as ei:
        yt._raise_transcript_unavailable(
            {
                "segments": [],
                "error": {"code": "language_not_available", "reason": "No tr"},
                "availableLanguages": [
                    {"languageCode": "en", "languageName": "English", "isAutoGenerated": True}
                ],
                "hasAutoCaptions": True,
                "requestedLanguage": "tr",
            },
            language="tr",
            suggestion={"endpoint": "/v1/youtube/audio-transcript", "estimatedCredits": 2},
        )
    detail = ei.value.detail
    assert isinstance(detail, dict)
    assert detail["code"] == "language_not_available"
    assert "suggestion" not in detail