/**
 * Generates the typed SDK surfaces from the canonical endpoint catalog
 * (backend/app/services/mcp_catalog.json, itself generated from
 * packages/captapi-mcp/src/catalog.ts):
 *
 *   - packages/captapi-sdk/src/generated.ts        (TypeScript SDK)
 *   - packages/captapi-python/captapi/_generated.py (Python SDK)
 *
 * Run:  npx tsx scripts/gen-sdk.mts
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

interface Param {
  name: string;
  type: "string" | "number" | "boolean";
  required: boolean;
  description: string;
}
interface Endpoint {
  tool: string;
  platform: string;
  name: string;
  path: string;
  credits: number;
  summary: string;
  params: Param[];
}

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const catalog: Endpoint[] = JSON.parse(
  readFileSync(join(root, "backend", "app", "services", "mcp_catalog.json"), "utf-8"),
);

const camel = (s: string) => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
const pascal = (s: string) => {
  const c = camel(s);
  return c.charAt(0).toUpperCase() + c.slice(1);
};

/** snake_case method name for an endpoint within its platform namespace. */
function methodSnake(e: Endpoint): string {
  if (e.tool === e.platform) return "get";
  if (e.tool.startsWith(e.platform + "_")) return e.tool.slice(e.platform.length + 1);
  // ad_library tools look like facebook_ad_library_search -> facebook_search
  const collapsed = e.tool.replace(`_${e.platform}`, "").replace(`${e.platform}_`, "");
  return collapsed || e.tool;
}

const platforms = [...new Set(catalog.map((e) => e.platform))];
const byPlatform = new Map(platforms.map((p) => [p, catalog.filter((e) => e.platform === p)]));

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------
const tsLines: string[] = [
  "// AUTO-GENERATED by scripts/gen-sdk.mts -- do not edit by hand.",
  'import { HttpCore, type ApiEnvelope, type CaptapiOptions } from "./core.js";',
  "",
];

for (const [platform, endpoints] of byPlatform) {
  const cls = `${pascal(platform)}Api`;
  // Param interfaces
  for (const e of endpoints) {
    const iface = `${pascal(e.tool)}Params`;
    tsLines.push(`export interface ${iface} {`);
    for (const p of e.params) {
      const doc = p.description.replace(/\*\//g, "*\\/");
      tsLines.push(`  /** ${doc} */`);
      tsLines.push(`  ${p.name}${p.required ? "" : "?"}: ${p.type};`);
    }
    tsLines.push("}", "");
  }
  tsLines.push(`export class ${cls} {`);
  tsLines.push("  constructor(private readonly core: HttpCore) {}");
  for (const e of endpoints) {
    const m = camel(methodSnake(e));
    const iface = `${pascal(e.tool)}Params`;
    const arg = e.params.length === 0 ? "params: Record<string, never> = {}" : e.params.every((p) => !p.required) ? `params: ${iface} = {}` : `params: ${iface}`;
    tsLines.push(`  /** ${e.name} — ${e.summary} (${e.credits} credit${e.credits === 1 ? "" : "s"}) */`);
    tsLines.push(`  ${m}(${arg}): Promise<ApiEnvelope> {`);
    tsLines.push(`    return this.core.get(${JSON.stringify(e.path)}, params);`);
    tsLines.push("  }");
  }
  tsLines.push("}", "");
}

tsLines.push("/** Captapi API client. Get your key at https://captapi.com/dashboard/api-keys */");
tsLines.push("export class Captapi {");
for (const platform of platforms) {
  tsLines.push(`  readonly ${camel(platform)}: ${pascal(platform)}Api;`);
}
tsLines.push("  constructor(options: CaptapiOptions = {}) {");
tsLines.push("    const core = new HttpCore(options);");
for (const platform of platforms) {
  tsLines.push(`    this.${camel(platform)} = new ${pascal(platform)}Api(core);`);
}
tsLines.push("  }");
tsLines.push("}");
tsLines.push("");

const tsOut = join(root, "packages", "captapi-sdk", "src", "generated.ts");
mkdirSync(dirname(tsOut), { recursive: true });
writeFileSync(tsOut, tsLines.join("\n"), "utf-8");
console.log(`wrote ${tsOut}`);

// ---------------------------------------------------------------------------
// Python
// ---------------------------------------------------------------------------
const PY_KEYWORDS = new Set(["from", "import", "class", "def", "return", "global", "async", "await", "pass", "type", "id", "filter", "format", "input"]);
const pyName = (n: string) => (PY_KEYWORDS.has(n) ? `${n}_` : n);
const pyType = (t: string) => (t === "string" ? "str" : t === "number" ? "float" : "bool");

function pySignature(e: Endpoint): { sig: string; body: string } {
  const parts: string[] = ["self"];
  if (e.params.length > 0) parts.push("*");
  const sorted = [...e.params].sort((a, b) => Number(b.required) - Number(a.required));
  for (const p of sorted) {
    parts.push(p.required ? `${pyName(p.name)}: ${pyType(p.type)}` : `${pyName(p.name)}: ${pyType(p.type)} | None = None`);
  }
  const dict = e.params.map((p) => `"${p.name}": ${pyName(p.name)}`).join(", ");
  return { sig: parts.join(", "), body: `{${dict}}` };
}

function pyDoc(e: Endpoint, indent: string): string[] {
  const lines = [`${indent}"""${e.name} — ${e.summary} (${e.credits} credit${e.credits === 1 ? "" : "s"})`];
  if (e.params.length > 0) {
    lines.push("");
    for (const p of e.params) {
      lines.push(`${indent}:param ${pyName(p.name)}: ${p.description.replace(/"""/g, '\\"\\"\\"')}`);
    }
  }
  lines.push(`${indent}"""`);
  return lines;
}

const pyLines: string[] = [
  "# AUTO-GENERATED by scripts/gen-sdk.mts -- do not edit by hand.",
  "from __future__ import annotations",
  "",
  "from typing import Any",
  "",
  "from ._transport import AsyncTransport, SyncTransport",
  "",
];

for (const [platform, endpoints] of byPlatform) {
  for (const variant of ["sync", "async"] as const) {
    const cls = variant === "sync" ? `${pascal(platform)}Api` : `Async${pascal(platform)}Api`;
    const transport = variant === "sync" ? "SyncTransport" : "AsyncTransport";
    pyLines.push(`class ${cls}:`);
    pyLines.push(`    def __init__(self, transport: ${transport}) -> None:`);
    pyLines.push("        self._t = transport");
    pyLines.push("");
    for (const e of endpoints) {
      const m = methodSnake(e);
      const { sig, body } = pySignature(e);
      const prefix = variant === "sync" ? "def" : "async def";
      const call = variant === "sync" ? `self._t.get("${e.path}", ${body})` : `await self._t.get("${e.path}", ${body})`;
      pyLines.push(`    ${prefix} ${m}(${sig}) -> dict[str, Any]:`);
      pyLines.push(...pyDoc(e, "        "));
      pyLines.push(`        return ${call}`);
      pyLines.push("");
    }
    pyLines.push("");
  }
}

for (const variant of ["sync", "async"] as const) {
  const cls = variant === "sync" ? "Captapi" : "AsyncCaptapi";
  const transport = variant === "sync" ? "SyncTransport" : "AsyncTransport";
  pyLines.push(`class ${cls}:`);
  pyLines.push(`    """Captapi API client. Get your key at https://captapi.com/dashboard/api-keys"""`);
  pyLines.push("");
  pyLines.push("    def __init__(self, api_key: str | None = None, *, base_url: str | None = None, timeout: float = 120.0) -> None:");
  pyLines.push(`        self._transport = ${transport}(api_key=api_key, base_url=base_url, timeout=timeout)`);
  for (const platform of platforms) {
    const api = variant === "sync" ? `${pascal(platform)}Api` : `Async${pascal(platform)}Api`;
    pyLines.push(`        self.${platform} = ${api}(self._transport)`);
  }
  pyLines.push("");
  if (variant === "sync") {
    pyLines.push("    def close(self) -> None:");
    pyLines.push("        self._transport.close()");
    pyLines.push("");
    pyLines.push("    def __enter__(self) -> \"Captapi\":");
    pyLines.push("        return self");
    pyLines.push("");
    pyLines.push("    def __exit__(self, *exc: object) -> None:");
    pyLines.push("        self.close()");
  } else {
    pyLines.push("    async def aclose(self) -> None:");
    pyLines.push("        await self._transport.aclose()");
    pyLines.push("");
    pyLines.push("    async def __aenter__(self) -> \"AsyncCaptapi\":");
    pyLines.push("        return self");
    pyLines.push("");
    pyLines.push("    async def __aexit__(self, *exc: object) -> None:");
    pyLines.push("        await self.aclose()");
  }
  pyLines.push("");
  pyLines.push("");
}

const pyOut = join(root, "packages", "captapi-python", "captapi", "_generated.py");
mkdirSync(dirname(pyOut), { recursive: true });
writeFileSync(pyOut, pyLines.join("\n"), "utf-8");
console.log(`wrote ${pyOut}`);
console.log(`platforms: ${platforms.length}, endpoints: ${catalog.length}`);
