// Social media slang dictionary. Terms sourced from the highest-volume
// "what does X mean" searches across TikTok, Snapchat, Instagram, and Discord.

export interface SlangTerm {
  term: string;
  meaning: string;
  platforms: string[]; // where it's most used
  example?: string;
}

export const SLANG_TERMS: SlangTerm[] = [
  { term: "PMO", meaning: "\u201cPiss me off\u201d — used when something annoys you. Occasionally \u201cput me on\u201d (recommend me something) depending on context.", platforms: ["TikTok", "Snapchat"], example: "people chewing loudly pmo" },
  { term: "NFS", meaning: "\u201cNot for sale\u201d on Instagram posts; \u201cno funny stuff\u201d or \u201cnew friends\u201d on Snapchat depending on context.", platforms: ["Snapchat", "Instagram"] },
  { term: "Green dot", meaning: "On Snapchat and Instagram, the green dot next to a name means the person is currently online / active in the app.", platforms: ["Snapchat", "Instagram"] },
  { term: "GTS", meaning: "\u201cGo to sleep\u201d — usually a late-night sign-off. Sometimes \u201cgood times\u201d.", platforms: ["Snapchat", "TikTok"] },
  { term: "WTW", meaning: "\u201cWhat's the word?\u201d — asking what's happening or what the plan is.", platforms: ["Snapchat"] },
  { term: "ONS", meaning: "\u201cOn snap\u201d (swearing something is true) — or \u201cone night stand\u201d in dating contexts.", platforms: ["Snapchat"] },
  { term: "S/U", meaning: "\u201cSwipe up\u201d — used on stories to point at the link or next content.", platforms: ["Snapchat", "Instagram"] },
  { term: "SFS", meaning: "\u201cShoutout for shoutout\u201d — cross-promoting each other's accounts.", platforms: ["Instagram", "Snapchat"] },
  { term: "FYP", meaning: "\u201cFor You Page\u201d — TikTok's main algorithmic feed. Landing on people's FYP means going viral.", platforms: ["TikTok"] },
  { term: "PFP", meaning: "\u201cProfile picture\u201d.", platforms: ["Discord", "TikTok", "Instagram"] },
  { term: "DWU", meaning: "\u201cDon't wait up\u201d — I'll be back late / don't expect a quick reply.", platforms: ["Snapchat"] },
  { term: "OOMF", meaning: "\u201cOne of my followers/friends\u201d — talking about someone without naming them.", platforms: ["X", "TikTok"] },
  { term: "IB", meaning: "\u201cInspired by\u201d — crediting the creator whose idea or sound you're using.", platforms: ["TikTok"] },
  { term: "DC", meaning: "\u201cDance credit\u201d — crediting the original choreographer of a dance.", platforms: ["TikTok"] },
  { term: "POV", meaning: "\u201cPoint of view\u201d — a video format where the viewer experiences the scene from a role.", platforms: ["TikTok", "Instagram"] },
  { term: "Ratio", meaning: "When a reply gets more likes than the original post — a sign the crowd disagrees with the original. \u201cRatio'd\u201d = publicly outvoted.", platforms: ["X", "TikTok"] },
  { term: "Rizz", meaning: "Charisma, especially in flirting. \u201cUnspoken rizz\u201d = attracting someone without saying anything.", platforms: ["TikTok"] },
  { term: "Gyat", meaning: "An exclamation of attraction (from \u201cgoddamn\u201d), typically reacting to curves.", platforms: ["TikTok"] },
  { term: "Delulu", meaning: "\u201cDelusional\u201d, used playfully — being unrealistically optimistic, often about a crush or goal.", platforms: ["TikTok"] },
  { term: "Sigma", meaning: "A \u201clone wolf\u201d success archetype; often ironic. \u201cWhat the sigma?\u201d is a meme expression of confusion.", platforms: ["TikTok"] },
  { term: "Skibidi", meaning: "Absurdist meme word from the Skibidi Toilet series — means nothing concrete; signals brainrot humor.", platforms: ["TikTok"] },
  { term: "Brainrot", meaning: "Content so absurd or addictive it \u201crots your brain\u201d — also the genre label for that content.", platforms: ["TikTok", "Discord"] },
  { term: "Aura", meaning: "Points-based charisma metaphor: impressive actions gain aura, embarrassing ones lose it (\u201c-1000 aura\u201d).", platforms: ["TikTok"] },
  { term: "Mewing", meaning: "Jawline-defining tongue posture trend; also a gesture (finger over lips) meaning \u201ccan't talk, mewing\u201d.", platforms: ["TikTok"] },
  { term: "Looksmaxxing", meaning: "Trying to maximize physical appearance through grooming, fitness, or more extreme measures.", platforms: ["TikTok"] },
  { term: "Bet", meaning: "\u201cOkay / deal / for sure\u201d — affirmative agreement.", platforms: ["Snapchat", "TikTok"] },
  { term: "Cap / No cap", meaning: "\u201cCap\u201d = a lie; \u201cno cap\u201d = no lie, for real.", platforms: ["TikTok", "Snapchat"] },
  { term: "Mid", meaning: "Mediocre, overrated — dismissive rating of something as average.", platforms: ["TikTok", "Discord"] },
  { term: "NPC", meaning: "\u201cNon-player character\u201d — someone acting robotic or without original thought; also a live-stream trend.", platforms: ["TikTok", "Discord"] },
  { term: "Ick", meaning: "A small behavior that instantly kills attraction (\u201che gave me the ick\u201d).", platforms: ["TikTok"] },
  { term: "Situationship", meaning: "A romantic connection without defined labels or commitment.", platforms: ["TikTok", "Instagram"] },
  { term: "Soft launch", meaning: "Hinting at a new relationship on social media without revealing the person (an arm, a second glass).", platforms: ["Instagram"] },
  { term: "Hard launch", meaning: "Officially revealing a relationship with a clear photo or tag.", platforms: ["Instagram"] },
  { term: "Canon event", meaning: "A formative (often painful) life experience that had to happen — \u201cdon't interfere, it's a canon event\u201d.", platforms: ["TikTok"] },
  { term: "Roman Empire", meaning: "A topic you think about constantly for no reason — \u201cwhat's your Roman Empire?\u201d", platforms: ["TikTok"] },
  { term: "Girl dinner", meaning: "A low-effort snack-plate meal presented as dinner.", platforms: ["TikTok"] },
  { term: "Golden retriever energy", meaning: "Friendly, loyal, easygoing personality (usually about partners).", platforms: ["TikTok"] },
  { term: "Beige flag", meaning: "A quirk in a partner that's neither good nor bad, just odd.", platforms: ["TikTok"] },
  { term: "Red flag / Green flag", meaning: "Warning sign vs. positive sign in a person or situation.", platforms: ["TikTok", "Instagram"] },
  { term: "Touch grass", meaning: "\u201cGo outside\u201d — telling someone they're too online.", platforms: ["Discord", "X"] },
  { term: "Lurker", meaning: "Someone who watches/reads but never posts or comments.", platforms: ["Discord", "Twitch", "Reddit"] },
  { term: "Alt", meaning: "An alternate account, separate from someone's main.", platforms: ["Discord", "X", "Instagram"] },
  { term: "Finsta", meaning: "\u201cFake Insta\u201d — a private second Instagram for close friends only.", platforms: ["Instagram"] },
  { term: "Spam account", meaning: "A casual second account for unfiltered posts (similar to finsta).", platforms: ["Instagram", "TikTok"] },
  { term: "DNI", meaning: "\u201cDo not interact\u201d — a profile note listing who the poster doesn't want engagement from.", platforms: ["X", "Discord", "TikTok"] },
  { term: "CW / TW", meaning: "\u201cContent warning\u201d / \u201ctrigger warning\u201d — a heads-up before sensitive content.", platforms: ["X", "Instagram", "TikTok"] },
  { term: "AFK", meaning: "\u201cAway from keyboard\u201d — temporarily unavailable.", platforms: ["Discord", "Twitch"] },
  { term: "Idle", meaning: "Discord status: online but inactive for a while (the yellow moon icon).", platforms: ["Discord"] },
  { term: "DND", meaning: "\u201cDo not disturb\u201d — Discord status that mutes notifications (red icon).", platforms: ["Discord"] },
  { term: "Nitro", meaning: "Discord's paid subscription — custom emoji anywhere, bigger uploads, HD streaming.", platforms: ["Discord"] },
  { term: "Poggers / Pog", meaning: "Excitement or hype, from the Twitch PogChamp emote.", platforms: ["Twitch", "Discord"] },
  { term: "KEKW", meaning: "Laughter emote on Twitch — equivalent to laughing out loud.", platforms: ["Twitch"] },
  { term: "Malding", meaning: "Mad + balding — raging hard, usually said of streamers losing their cool.", platforms: ["Twitch"] },
  { term: "Copium", meaning: "Cope + opium — jokingly \u201cinhaled\u201d when denying a hard truth.", platforms: ["Twitch", "Discord"] },
  { term: "Hopium", meaning: "Hope + opium — irrational optimism about an unlikely outcome.", platforms: ["Twitch", "X"] },
  { term: "Sus", meaning: "Suspicious, sketchy — popularized by Among Us.", platforms: ["Discord", "TikTok"] },
  { term: "Based", meaning: "Confidently yourself regardless of others' opinions; agreement with a bold take.", platforms: ["X", "Discord"] },
  { term: "Cooked", meaning: "Doomed or exhausted (\u201cI'm cooked\u201d). \u201cLet him cook\u201d = let him finish, he's onto something.", platforms: ["TikTok", "Discord"] },
  { term: "Yapping", meaning: "Talking too much about nothing (\u201cwhat is bro yapping about\u201d).", platforms: ["TikTok", "Discord"] },
  { term: "Glazing", meaning: "Excessively praising someone — over-the-top fanboying.", platforms: ["TikTok", "Discord"] },
  { term: "Farming", meaning: "Doing something repeatedly just for engagement or points (\u201cengagement farming\u201d, \u201caura farming\u201d).", platforms: ["X", "TikTok"] },
  { term: "Vanish mode", meaning: "Instagram/Messenger DM mode where messages disappear after being seen — and screenshots notify the other person.", platforms: ["Instagram", "Facebook"] },
  { term: "Time sensitive", meaning: "Snapchat notification label that bypasses iPhone Focus/silent modes for messages the app deems urgent.", platforms: ["Snapchat"] },
  { term: "Restrict", meaning: "Instagram feature: a restricted person's comments become invisible to others and their DMs go to requests — without them knowing.", platforms: ["Instagram"] },
];
